font_family       JetBrainsMono Nerd Font
font_size 15.0

map cmd+w close_window
map cmd+] next_window
map cmd+[ previous_window
map cmd+shift+d new_window
map cmd+d new_window
map cmd+shift+backspace goto_layout fat
map cmd+shift+enter goto_layout stack


allow_remote_control yes

tab_bar_style powerline
tab_powerline_style slanted
active_tab_font_style bold
inactive_tab_font_style normal

# BEGIN_KITTY_THEME
# GitHub Light
include current-theme.conf
# END_KITTY_THEME
