font_family       JetBrainsMono Nerd Font
font_size 15.0

# macOS 特有滚动快捷键
map ctrl+k scroll_line_up
map ctrl+j scroll_line_down
map ctrl+u scroll_page_up
map ctrl+d scroll_page_down

map cmd+d new_window
map cmd+shift+d new_window
map cmd+w close_window
map cmd+] next_window
map cmd+[ previous_window
map cmd+ctrl+l next_window
map cmd+ctrl+h previous_window

map cmd+shift+backspace goto_layout fat
map cmd+shift+enter goto_layout stack
map cmd+shift+] next_tab
map cmd+shift+[ previous_tab
map cmd+shift+. move_tab_forward
map cmd+shift+, move_tab_backward

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

map alt+1 first_window
map alt+2 second_window
map alt+3 third_window
map alt+4 fourth_window
map alt+5 fifth_window
map alt+6 sixth_window
map alt+7 seventh_window
map alt+8 eighth_window
map alt+9 ninth_window

# allow_remote_control yes

tab_bar_style powerline
tab_powerline_style slanted
active_tab_font_style bold
inactive_tab_font_style normal

# BEGIN_KITTY_THEME
# GitHub Light
include current-theme.conf
# END_KITTY_THEME
